jobs:
  build:
    name: ${{ matrix.pretty_name }}
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Build container image
      run: docker build -t "aut-${{ matrix.dockerfile }}" ${{ matrix.build_args }}
        -f "dockerfiles/${{ matrix.dockerfile }}" .
    - name: Run tests
      run: docker run -t -e PYTHONPATH="/opt/pre/${{ matrix.product }}-${{ matrix.version
        }}/lib" -e PRE="${{ matrix.pre }}" -e PRODUCT="${{ matrix.product }}" -e VERSION="${{
        matrix.version }}" -e PPA="${{ matrix.ppa }}" -e DOCKERFILE="${{ matrix.dockerfile
        }}" "aut-${{ matrix.dockerfile }}"
    strategy:
      fail-fast: false
      matrix:
        include:
        - build_args: ''
          dockerfile: centos7
          pre: pip
          pretty_name: centos7 pip 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: centos7
          pre: pip
          pretty_name: centos7 pip 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: centos7
          pre: pip
          pretty_name: centos7 pip 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: centos7
          pre: pip
          pretty_name: centos7 pip 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: centos7
          pre: pip-latest
          pretty_name: centos7 pip-latest 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: centos7
          pre: pip-latest
          pretty_name: centos7 pip-latest 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: centos7
          pre: pip-latest
          pretty_name: centos7 pip-latest 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: centos7
          pre: pip-latest
          pretty_name: centos7 pip-latest 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: centos7
          pre: tar
          pretty_name: centos7 tar 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: centos7
          pre: tar
          pretty_name: centos7 tar 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: centos7
          pre: tar
          pretty_name: centos7 tar 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: centos7
          pre: tar
          pretty_name: centos7 tar 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: centos7
          pre: rpm
          pretty_name: centos7 rpm 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: centos8
          pre: pip
          pretty_name: centos8 pip 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: centos8
          pre: pip
          pretty_name: centos8 pip 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: centos8
          pre: pip
          pretty_name: centos8 pip 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: centos8
          pre: pip
          pretty_name: centos8 pip 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: centos8
          pre: pip-latest
          pretty_name: centos8 pip-latest 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: centos8
          pre: pip-latest
          pretty_name: centos8 pip-latest 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: centos8
          pre: pip-latest
          pretty_name: centos8 pip-latest 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: centos8
          pre: pip-latest
          pretty_name: centos8 pip-latest 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: centos8
          pre: tar
          pretty_name: centos8 tar 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: centos8
          pre: tar
          pretty_name: centos8 tar 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: centos8
          pre: tar
          pretty_name: centos8 tar 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: centos8
          pre: tar
          pretty_name: centos8 tar 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: py310-rc-buster
          pre: pip
          pretty_name: py310-rc-buster pip 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: py310-rc-buster
          pre: pip
          pretty_name: py310-rc-buster pip 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: py310-rc-buster
          pre: pip
          pretty_name: py310-rc-buster pip 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: py310-rc-buster
          pre: pip
          pretty_name: py310-rc-buster pip 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: py310-rc-buster
          pre: tar
          pretty_name: py310-rc-buster tar 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: py310-rc-buster
          pre: tar
          pretty_name: py310-rc-buster tar 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: py310-rc-buster
          pre: tar
          pretty_name: py310-rc-buster tar 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: py310-rc-buster
          pre: tar
          pretty_name: py310-rc-buster tar 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: ubi7
          pre: pip
          pretty_name: ubi7 pip 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: ubi7
          pre: pip
          pretty_name: ubi7 pip 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: ubi7
          pre: pip
          pretty_name: ubi7 pip 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: ubi7
          pre: pip
          pretty_name: ubi7 pip 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: ubi7
          pre: tar
          pretty_name: ubi7 tar 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: ubi7
          pre: tar
          pretty_name: ubi7 tar 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: ubi7
          pre: tar
          pretty_name: ubi7 tar 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: ubi7
          pre: tar
          pretty_name: ubi7 tar 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: ubi7
          pre: rpm
          pretty_name: ubi7 rpm 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: ubi7-py35
          pre: pip-latest
          pretty_name: ubi7-py35 pip-latest 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: ubi7-py35
          pre: pip-latest
          pretty_name: ubi7-py35 pip-latest 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: ubi7-py35
          pre: pip-latest
          pretty_name: ubi7-py35 pip-latest 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: ubi7-py35
          pre: pip-latest
          pretty_name: ubi7-py35 pip-latest 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: ubi8
          pre: pip
          pretty_name: ubi8 pip 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: ubi8
          pre: pip
          pretty_name: ubi8 pip 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: ubi8
          pre: pip
          pretty_name: ubi8 pip 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: ubi8
          pre: pip
          pretty_name: ubi8 pip 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: ubi8
          pre: tar
          pretty_name: ubi8 tar 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: ubi8
          pre: tar
          pretty_name: ubi8 tar 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: ubi8
          pre: tar
          pretty_name: ubi8 tar 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: ubi8
          pre: tar
          pretty_name: ubi8 tar 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: ubuntu2004
          pre: pip
          pretty_name: ubuntu2004 pip 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: ubuntu2004
          pre: pip
          pretty_name: ubuntu2004 pip 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: ubuntu2004
          pre: pip
          pretty_name: ubuntu2004 pip 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: ubuntu2004
          pre: pip
          pretty_name: ubuntu2004 pip 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: ubuntu2004
          pre: tar
          pretty_name: ubuntu2004 tar 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: ubuntu2004
          pre: tar
          pretty_name: ubuntu2004 tar 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: ubuntu2004
          pre: tar
          pretty_name: ubuntu2004 tar 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: ubuntu2004
          pre: tar
          pretty_name: ubuntu2004 tar 2.11.0
          product: ansible-core
          version: 2.11.0
        - PPA: ansible/ansible-2.10
          build_args: ''
          dockerfile: ubuntu2004
          pre: ppa
          pretty_name: ubuntu2004 ppa ansible/ansible-2.10 2.10.8
          product: ansible-base
          version: 2.10.8
        - PPA: ansible/ansible
          build_args: ''
          dockerfile: ubuntu2004
          pre: ppa
          pretty_name: ubuntu2004 ppa ansible/ansible 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip
          pretty_name: ubuntu1804 pip 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip
          pretty_name: ubuntu1804 pip 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip
          pretty_name: ubuntu1804 pip 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip
          pretty_name: ubuntu1804 pip 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip-latest
          pretty_name: ubuntu1804 pip-latest 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip-latest
          pretty_name: ubuntu1804 pip-latest 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip-latest
          pretty_name: ubuntu1804 pip-latest 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: ubuntu1804
          pre: pip-latest
          pretty_name: ubuntu1804 pip-latest 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: ubuntu1804
          pre: tar
          pretty_name: ubuntu1804 tar 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: ubuntu1804
          pre: tar
          pretty_name: ubuntu1804 tar 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: ubuntu1804
          pre: tar
          pretty_name: ubuntu1804 tar 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: ubuntu1804
          pre: tar
          pretty_name: ubuntu1804 tar 2.11.0
          product: ansible-core
          version: 2.11.0
        - PPA: ansible/ansible-2.9
          build_args: ''
          dockerfile: ubuntu1804
          pre: ppa
          pretty_name: ubuntu1804 ppa ansible/ansible-2.9 2.9.20
          product: ansible
          version: 2.9.20
        - PPA: ansible/ansible-2.10
          build_args: ''
          dockerfile: ubuntu1804
          pre: ppa
          pretty_name: ubuntu1804 ppa ansible/ansible-2.10 2.10.8
          product: ansible-base
          version: 2.10.8
        - PPA: ansible/ansible
          build_args: ''
          dockerfile: ubuntu1804
          pre: ppa
          pretty_name: ubuntu1804 ppa ansible/ansible 2.9.20
          product: ansible
          version: 2.9.20
        - PPA: ansible/ansible
          build_args: ''
          dockerfile: ubuntu1804
          pre: ppa
          pretty_name: ubuntu1804 ppa ansible/ansible 2.10.8
          product: ansible-base
          version: 2.10.8
    timeout-minutes: 20
  macos-build:
    name: ${{ matrix.pretty_name }}
    runs-on: ${{ matrix.dockerfile }}
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - env:
        DOCKERFILE: ${{ matrix.dockerfile }}
        PPA: ${{ matrix.ppa }}
        PRE: ${{ matrix.pre }}
        PRODUCT: ${{ matrix.product }}
        VERSION: ${{ matrix.version }}
      name: Run tests
      run: bash entrypoint.sh
    strategy:
      fail-fast: false
      matrix:
        include:
        - build_args: ''
          dockerfile: macos-10.15
          pre: pip
          pretty_name: macos-10.15 pip 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: macos-10.15
          pre: pip
          pretty_name: macos-10.15 pip 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: macos-10.15
          pre: pip
          pretty_name: macos-10.15 pip 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: macos-10.15
          pre: pip
          pretty_name: macos-10.15 pip 2.11.0
          product: ansible-core
          version: 2.11.0
        - build_args: ''
          dockerfile: macos-10.15
          pre: tar
          pretty_name: macos-10.15 tar 2.9.20
          product: ansible
          version: 2.9.20
        - build_args: ''
          dockerfile: macos-10.15
          pre: tar
          pretty_name: macos-10.15 tar 2.10.8
          product: ansible-base
          version: 2.10.8
        - build_args: ''
          dockerfile: macos-10.15
          pre: tar
          pretty_name: macos-10.15 tar 2.11.0rc2
          product: ansible-core
          version: 2.11.0rc2
        - build_args: ''
          dockerfile: macos-10.15
          pre: tar
          pretty_name: macos-10.15 tar 2.11.0
          product: ansible-core
          version: 2.11.0
    timeout-minutes: 20
name: Ansible User Artifact Tests
'on':
  pull_request: null
  push: null
  schedule:
  - cron: 0 13 * * *

